name = "ifest-management"
main = ".open-next/worker.js"
compatibility_date = "2026-07-20"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", not_found_handling = "none" }

[placement]
mode = "smart"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "sintuwu-ifest"
preview_bucket_name = "sintuwu-ifest"



